### ISSUE TITLE
session debug is always output

### ISSUE THREAD

**Issue by arcanez** [ollyg/Net-CLI-Interact#21]
in **Net::CLI::Interact::Role::Engine**,
```
sub _trigger_last_actionset {
    my ($self, $new) = @_;
    $self->logger->log('prompt', 'notice',
        sprintf ('output matching prompt was "%s"', $new->item_at(-1)->response));
    if (Class::Load::is_class_loaded('Data::Printer')) {
        $self->logger->log('object', 'debug', Data::Printer::p($new));
    }
}
```
this is always outputting session debug to STDERR for me

```
    if (Class::Load::is_class_loaded('Data::Printer')) {
        Data::Printer::p($new, output => \my $debug);
        $self->logger->log('object', 'debug', $debug);
    }
```
fixes the issue for me, but I have not done testing in the other direction.

**Comment by ollyg** [comment]
Yes, looks like the behaviour of Data::Printer::p() changed in version 0.36 a few months ago. I would have personally bumped the major version for that!
https://metacpan.org/changes/distribution/Data-Printer#L33

**Comment by ollyg** [comment]
Net-CLI-Interact-2.200006 just sent to CPAN. Many thanks!!
