### ISSUE TITLE
HP Procurve uses ANSI terminal codes

### ISSUE THREAD

**Issue by ollyg** [ollyg/Net-CLI-Interact#22]
From: https://rt.cpan.org/Ticket/Display.html?id=118747
Opened by: Vlad Zaitsev <vladzaitsev at gmail.com>

HP Procurve uses ANSI terminal codes so prompt default propmt patterd does
not match and writing custom is really the pain.  Guys from netmico project
make ANSI cleanup for such devices
https://github.com/ktbyers/netmiko/blob/47c597a674ac8d7e8a2c18388bfb3dbcb205b273/netmiko/base_connection.py

def strip_ansi_escape_codes(string_buffer):

Could we add such funtionality to Net::Applience? May activated via
parameter foe new() ?

**Comment by Zaitsev** [comment]
Hi Oliver. Any news about issue?

**Comment by ollyg** [comment]
Hi, yes, I think it's a very good idea, but I've not had the time yet to implement a patch.

**Comment by Zaitsev** [comment]
May be I can help, I'm about to build new release so I could implement fix on-the-go. you wrote "Hi Vlad, I think I've worked out an easy way to do this. Are you available for testing?" some time ago...

**Comment by ollyg** [comment]
OK I will take a look at the source and try to refresh my memory :-)

**Comment by Zaitsev** [comment]
Im using this clear function and it works pretty well with ProCurve J9279A Switch 2510G-24
[EscapeANSI.zip](https://github.com/ollyg/Net-CLI-Interact/files/1158856/EscapeANSI.zip)
```perl
package Net::CLI::Interact::Role::FindMatch;
....
use NGNMS::EscapeANSI qw /escape_ansi/;
....
sub find_match {
...
    escape_ansi(\$text);
    use List::Util 'first';
    return first { $text =~ $_ } @$matches;
}
```

```perl 
package Net::CLI::Interact::Transport::Wrapper::Base;
...
sub do_action {
 ... 
        while ($self->pump) {
            # remove control characters
            (my $buffer = $self->buffer) =~ s/[\000-\010\013\014\016-\032\034-\037]//g;
            escape_ansi(\$buffer);

```

**Comment by ollyg** [comment]
Hi, I committed c7c8f3e and released version 2.200007_001 to CPAN.

Please take a look, test, and let me know how you get on!

**Comment by ollyg** [comment]
(sorry, I will also update the changelog to give you credit!)

**Comment by Zaitsev** [comment]
Hi Oliver. Thanks your for help. I've created pull-request cause yours solution not works as intendet. Pls review it...
