### ISSUE TITLE
phrasebooks/cisco/hp/pb: (unused) prompt basic makes logging in impossible

### ISSUE THREAD

**Issue by ollyg** [ollyg/Net-CLI-Interact#25]
Migrated from [rt.cpan.org #121523](https://rt.cpan.org/Ticket/Display.html?id=121523) (status was 'new')

Requestors:
* alexz@opmantek.com

From alexz@opmantek.com on 2017-05-04 03:38:34:

the hp phrasebook as shipped contains the prompt 'basic', which
overlaps and conflicts with the pass(word) prompt (which is inherited from
the cisco pb). (as far as i can tell from reading the source
of n::a::s and n::c::i, prompt basic isn't even used anywhere?)

that prompt basic matches on /: ?$/ causes n::a::s to fail logging
in on hp procurve devices because the device requests the password
with "username's password: " and basic catches that before the pass(word)
prompt can fire. see the following debug snippet:

[   0.009026] pr finding prompt
[   0.012213] tr creating Net::Telnet wrapper for ssh
[   0.012977] tr connecting with:  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o PubkeyAuthentication=no -e none -l manager 1.2.3.4
...
[   1.271511] pr   nope, doesn't (yet) match basic
[   1.271874] pr   nope, doesn't (yet) match pass
[   1.272355] pr   nope, doesn't (yet) match generic
[   1.272724] pr   nope, doesn't (yet) match user
[   1.272991] pr   nope, doesn't (yet) match configure
[   1.273206] pr   nope, doesn't (yet) match privileged
[   1.273770] pr   nope, doesn't (yet) match prompt
....
[   1.318968] du   SEEN:
Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hp.com/networking/register

manager@1.2.3.4's password: 
[   1.319490] pr  hit, matches prompt basic
[   1.319834] pr  prompt has been set to (?^:: ?$)
[   1.324885] pr output matching prompt was "manager@1.2.3.4's password: "
[   1.325330] di  trimmed command response:
Warning: Permanently added '1.2.3.4' (RSA) to the list of known hosts.
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hp.com/networking/register
....

and the password is never sent and the session eventually fails
with "login failed to remote host - prompt does not match"

regards
az

-- 
Alexander Zangerl
email: alexz@opmantek.com
skype: alex.zangerl
mobile: +61 415 482 341
web: https://community.opmantek.com/

**Comment by az143** [comment]
an updated phrasebook was pushed.
