### ISSUE TITLE
session's wake_up type does not match the docs

### ISSUE THREAD

**Issue by ollyg** [ollyg/Net-CLI-Interact#29]
Migrated from [rt.cpan.org #123052](https://rt.cpan.org/Ticket/Display.html?id=123052) (status was 'new')

Requestors:
* alexz@opmantek.com

Attachments:
* [session-wakeup.patch](https://rt.cpan.org/Ticket/Attachment/1748579/940570/session-wakeup.patch)

From alexz@opmantek.com on 2017-09-15 03:43:00:

the docs say it's an integer, but the code sets it up as a pseudo-boolean.

as n::c::i does treat this as an integer, i think the documented behaviour
is the right choice, and the moo code in session.pm is incorrect.
patch attached.

regards
az

**Comment by az143** [comment]
i've just applied this patch.
