### ISSUE TITLE
ssh key pass-phrase macro

### ISSUE THREAD

**Issue by Zaitsev** [ollyg/Net-CLI-Interact#34]
Add default `ssh key pass-phrase` to all phrasebooks,
This macro matches against ssh-key password prompt.
When it is present in phrasebook, it allows to use  `-i  /path/to/ssh_key` connection options with password-protected keys, `password` options used as key-pass
We use it now, but adding it to all phrase-books is boring.
Could this macro be added to all phrase-books at once?
May be there is method to add custom macro on-the-fly?
```
## ssh key prompt
prompt ssh_key
    match /[Ee]nter passphrase for key.+: $/
                                             
```

**Comment by ollyg** [comment]
Hi @Zaitsev this is a good idea, to have macros available to all phrasebooks. However it will require a little code on my side - I will look into this soon. Many thanks for the request!

**Comment by Zaitsev** [comment]
Hi @ollyg , thanks for response.
While add all-phrasebook-macros is good idea, could u consider adding _array_ of custom phrasebooks to session? Phrasebook module itself use array of directories' names

**Comment by ollyg** [comment]
Hi @Zaitsev are you able to give an example of what you would like to see in code/config? Thanks.

**Comment by Zaitsev** [comment]
In [Phrasebook](https://metacpan.org/pod/release/OLIVER/Net-CLI-Interact-2.200002/lib/Net/CLI/Interact/Phrasebook.pm#library-=>-$directory-|-\@directories)
we could pass @directories,
_but _
in [Session](https://metacpan.org/pod/Net::Appliance::Session#add_library-=>-$directory) it redused only to 1 directory
So, if we could pass @directories to `Session::add_library` we could mix-in common phrasebooks

**Comment by ollyg** [comment]
Great! Version Net::Appliance::Session 4.300001 on its way to CPAN now - let me know how you get on.
