### ISSUE TITLE
NX-OS status bar woes

### ISSUE THREAD

**Issue by rc9000** [ollyg/Net-CLI-Interact#45]
NX-OS has a cool progress bar when saving the config: 

```
router1# copy running-config startup-config
[########################################] 100%
Copy complete, now saving to disk (please wait)...
```

this seems to sometimes, but not always, match the generic prompt:
```
[   0.731668] di queueing data for send: "copy running-config startup-config"
[   0.936737] pr output matching prompt was "[#############"
```

any hot ideas how I could prevent this? I don't even understand why it matches, the generic prompt is `match /[\/a-zA-Z0-9._\[\]-]+ ?(?:\(config[^)]*\))? ?[#>] ?$/`
I've also tried the improved NX-OS prompt from  https://github.com/ollyg/Net-CLI-Interact/commit/01821cea86e7a67a73ebcf1738051c5f0d09ceaa but that also fails the same way.

It really seems to be a timing issue, because when enabling `$session->set_global_log_at('debug');` it never happens, which of course does not help with debugging :)

**Comment by rc9000** [comment]
Actually I see how the original prompt could match due to the `\[` in the first character list, but I removed `\[\]` to no avail. After some more brute-forcing, what seems to work is using negative lookaround like so:

```
# this seems to work
prompt generic
    match /[\/a-zA-Z0-9._-]+ ?(?:\(config[^)]*\))? ?(?<!#)(#|>)(?!#) ?$/
```

That could do for a workaround, but I'm still a bit puzzled why it would even look at an incomplete line like this.

**Comment by ollyg** [comment]
Hi @rc9000!

Hmm, you should also get a log line from the "tr" (transport) category something like
`output matched %s, storing and returning`
from https://github.com/ollyg/Net-CLI-Interact/blob/master/lib/Net/CLI/Interact/Transport/Wrapper/Base.pm#L115

Or set log level to debug and you get to see each character stream in and be matched. It's noisy!

Anyway, first comment is that there isn't the concept of "incomplete line" in NCI, it just periodically checks the buffer for matches and if there are multiple lines, it will check each, but if there's an incomplete line, it's just a line without a carriage-return/newline char, NCI doesn't wait for the carriage-return.

Second comment, is that what interests me is that "[#" *does* match the prompt (https://www.debuggex.com/). So I wonder if that matches when the progress bar starts, and somehow there's a race condition (bug) and then the output you see is more of the input than was matched.

Third comment, is that the better fix is probably to make sure the "[]" are balanced, as I guess they were intended to be something like "blahblah[foo]#>" in the prompt, and not just a lonely "[".

I'll give it more thought.

**Comment by rc9000** [comment]
Thanks for the inputs. I did some more poking around and finally found that not the generic, but the privileged prompt was matching the write status bar. I did not expect that at all since the session is started through Net::Appliance::Session with `do_privileged_mode => 0`, but obviously that does not prevent a match with the privileged prompt. Which of course is just `match /# ?$/` and will often match partial `[###################                     ]  46%` buffers.

I'm now just using a custom phrasebook for when we are executing the copy command that sets both prompts to something that closely matches the prompt in our naming scheme, so there's no chance to trip up on any [# and # :

```
# cisco/pb

# match e.g. "nexus-core-pe1# " quite exactly to not trip
# on partial substrings of [###################                     ]  46%
# overwrite both privileged and generic prompt defaults
prompt generic
    match /[a-zA-Z0-9._-]{10}# ?$/

prompt privileged
    match /[a-zA-Z0-9._-]{10}# ?$/
```

So everything fine with the good ole Net::CLI::Interact. I'm glad we didn't have to go to _"the better fix is probably to make sure the "[]" are balanced"_, this gives me strong vibes of this [classic piece of computer literature](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454) :)
